# Generated by Django 4.2.4 on 2023-09-12 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_img',
            field=models.CharField(default='https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.flaticon.com%2Ffree-icon%2Fplaceholder_4901689&psig=AOvVaw2pipHs9W_rgMxiIVt3IYQC&ust=1694601222709000&source=images&cd=vfe&opi=89978449&ved=0CBAQjRxqFwoTCPius-bvpIEDFQAAAAAdAAAAABAO', max_length=500),
        ),
    ]
