# Generated by Django 4.2.4 on 2023-09-13 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_alter_item_item_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='for_user',
            field=models.CharField(default='xyz', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='prod_code',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='Item_desc',
            field=models.CharField(default='Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ipsum exercitationem deserunt quidem vel magni saepe voluptates minima ab ex! Quam, quae atque nulla accusamus cum illum. Aliquam aspernatur modi ipsum?', max_length=500),
        ),
    ]
